name: Cypress Tests

on: [push]


jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo, submodules and composite actions
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci
      - run: npm tests --headless