name: Cypress Tests

on: [push]


jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: npm
      - run: npm ci
      - run: npm tests --headless